language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: q5tQoP5JN/AokBMKdbuwdNMvFFeygSd23l3pr8DdZqsBdn2VLQ2odg7ddZFt+oy+DMb1foFbwv1SCNb9Y/rUfXc4+znvaWU6ne/2fpi8FRliSYSg30zBNX0yhhQq37/HioIs2zIBfqglhEROwFeGXkQYLO980qGL0jQNhIPx1EWrQRlJv9ZsxTWbNZyrvjuj1AL2WfBSGogDY8JteaZc9BVSQQ6O0KMMBUrjKeeSsaEnqfHwR9DhQUylFwnbgQ6exh9q99CgSPu+W5qdwJUK6AxrvxoqPCxw+43U40aiNNaMo9ByNY8sNeDY6WdYOVwBTShHmWR3kmZz6F4o2Lt5amE76VqcUe63xh1ZpqiA6X60JL/+MMJRNa+thQJM7h58W6ymJ7CMrrdMkDevHhHo0lyl7EAUCbWApkS4RJKo/LJJZDjH38PkU2/ncbLCB+q18n5D6rXPboiuX5iSZeDLrBg+6GD4628hdA7z68D4s0O416en+m5yFgYNRKss0e+lEtXLM0Wp2L5iGGNZlcXX0mMTebVyCulHRedYjt1T8HPpZS7mkghpZzwO79Dc0cphpqhHL04I6mtLIddJjGCWUm4JOLoJJckcHiMrJe9fIvjFsDJQ2ZELYEa5evKtr43B1UT6lH6ehet0hhbBikqAby7fA3TEfJYLyxnXw2AAUHA=
  app: fast-island-26040
  on:
    repo: aaltamirano1/challenge-add-tests-to-mongoose-app
