language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: oak4/GVAYp8RRaJQmdfOgC9LqS+wIVrd13YREycjDMJVQ6gzRIFrcW6E8xaeMxjyGFertTDz3dw7tdMP0f5LdajvnNI0xbOG30U08HGox27nS40ofOp2n+v9pTipmsbdzoZNB9hpQh924g46RIQeLLKNIuhH5ZHwvfDjTS6Kd9tF58AcNQClqQpLfqKCuT/X0BlLoWX3JuN1I2uyEjjpzVblw648yUcdI7DIeW9EUK9qEQ/oTAmgn2GOm17nwaU8HWcKDQLgeO89X81lShl7Tk3TISh2ox1f4VEA/nwRVwgkLY30Ult3ds9UC5uuttEnunrT9Qy6ZVce/e134CZpPAgyx5qHT2nA7IbqLgXhMpFPR3hCaoX0oxtb2Z79QpRWLUiHtdB5GaefpTLUmac2/1to9RNc73yd3eZUyq4he6Sll09UT3Sr9k1ktwMy31pPUjFKgybICVer7sp6cUnZxWIUE376G5jW95u8gsC4HGRsA0xIuwLBAI9WdhlAA/bOacqGLDTga/ZX7VVm+f3qFiP9T50wXnziJSrEJvzwodDmJthKP/2dZy8TejituyuuzLhyDhVmKv7p8KdtrtdODIm7T91n7NlXR8JNGdqSQwvMeUygIo62lLwJpr5Cxwwb3AXidGbBI43UvRGI6m3SM7h8z8PMDu2n/gLVZ4JNbgc=
  app: fast-island-26040
  on:
    repo: aaltamirano1/challenge-add-tests-to-mongoose-app
